// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Adventures implements SupadartClass<Adventures> {
  final String id;
  final String chapterId;
  final String campaignId;
  final String title;
  final String? description;
  final Map<String, dynamic> content;
  final String orderNumber;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Adventures({
    required this.id,
    required this.chapterId,
    required this.campaignId,
    required this.title,
    this.description,
    required this.content,
    required this.orderNumber,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'adventures';
  static String get c_id => 'id';
  static String get c_chapterId => 'chapter_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_title => 'title';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_orderNumber => 'order_number';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Adventures> converter(List<Map<String, dynamic>> data) {
    return data.map(Adventures.fromJson).toList();
  }

  static Adventures converterSingle(Map<String, dynamic> data) {
    return Adventures.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? chapterId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    String? orderNumber,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (chapterId != null) 'chapter_id': chapterId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (orderNumber != null) 'order_number': orderNumber,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String chapterId,
    required String campaignId,
    required String title,
    String? description,
    required Map<String, dynamic> content,
    required String orderNumber,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      chapterId: chapterId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      orderNumber: orderNumber,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? chapterId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    String? orderNumber,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      chapterId: chapterId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      orderNumber: orderNumber,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Adventures.fromJson(Map<String, dynamic> jsonn) {
    return Adventures(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      chapterId: jsonn['chapter_id'] != null
          ? jsonn['chapter_id'].toString()
          : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      title: jsonn['title'] != null ? jsonn['title'].toString() : '',
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : <String, dynamic>{},
      orderNumber: jsonn['order_number'] != null
          ? jsonn['order_number'].toString()
          : '',
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? chapterId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    String? orderNumber,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (chapterId != null) 'chapter_id': chapterId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (orderNumber != null) 'order_number': orderNumber,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      chapterId: chapterId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      orderNumber: orderNumber,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  Adventures copyWith({
    Object? id = _unset,
    Object? chapterId = _unset,
    Object? campaignId = _unset,
    Object? title = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? orderNumber = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return Adventures(
      id: id == _unset ? this.id : id as String,
      chapterId: chapterId == _unset ? this.chapterId : chapterId as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      title: title == _unset ? this.title : title as String,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>,
      orderNumber: orderNumber == _unset
          ? this.orderNumber
          : orderNumber as String,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
