// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Campaigns implements SupadartClass<Campaigns> {
  final String id;
  final String createdBy;
  final String title;
  final String? description;
  final Map<String, dynamic> content;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Campaigns({
    required this.id,
    required this.createdBy,
    required this.title,
    this.description,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'campaigns';
  static String get c_id => 'id';
  static String get c_createdBy => 'created_by';
  static String get c_title => 'title';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Campaigns> converter(List<Map<String, dynamic>> data) {
    return data.map(Campaigns.fromJson).toList();
  }

  static Campaigns converterSingle(Map<String, dynamic> data) {
    return Campaigns.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? createdBy,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (createdBy != null) 'created_by': createdBy,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String createdBy,
    required String title,
    String? description,
    required Map<String, dynamic> content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      createdBy: createdBy,
      title: title,
      description: description,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? createdBy,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      createdBy: createdBy,
      title: title,
      description: description,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Campaigns.fromJson(Map<String, dynamic> jsonn) {
    return Campaigns(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      createdBy: jsonn['created_by'] != null
          ? jsonn['created_by'].toString()
          : '',
      title: jsonn['title'] != null ? jsonn['title'].toString() : '',
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : <String, dynamic>{},
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? createdBy,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (createdBy != null) 'created_by': createdBy,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      createdBy: createdBy,
      title: title,
      description: description,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  Campaigns copyWith({
    Object? id = _unset,
    Object? createdBy = _unset,
    Object? title = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return Campaigns(
      id: id == _unset ? this.id : id as String,
      createdBy: createdBy == _unset ? this.createdBy : createdBy as String,
      title: title == _unset ? this.title : title as String,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
