// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class CampaignAccess implements SupadartClass<CampaignAccess> {
  final String id;
  final String campaignId;
  final String userId;
  final String role;
  final String? sourceGroupId;
  final DateTime createdAt;
  final DateTime updatedAt;

  const CampaignAccess({
    required this.id,
    required this.campaignId,
    required this.userId,
    required this.role,
    this.sourceGroupId,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'campaign_access';
  static String get c_id => 'id';
  static String get c_campaignId => 'campaign_id';
  static String get c_userId => 'user_id';
  static String get c_role => 'role';
  static String get c_sourceGroupId => 'source_group_id';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<CampaignAccess> converter(List<Map<String, dynamic>> data) {
    return data.map(CampaignAccess.fromJson).toList();
  }

  static CampaignAccess converterSingle(Map<String, dynamic> data) {
    return CampaignAccess.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? campaignId,
    String? userId,
    String? role,
    String? sourceGroupId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (campaignId != null) 'campaign_id': campaignId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (sourceGroupId != null) 'source_group_id': sourceGroupId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String campaignId,
    required String userId,
    required String role,
    String? sourceGroupId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      campaignId: campaignId,
      userId: userId,
      role: role,
      sourceGroupId: sourceGroupId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? campaignId,
    String? userId,
    String? role,
    String? sourceGroupId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      campaignId: campaignId,
      userId: userId,
      role: role,
      sourceGroupId: sourceGroupId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory CampaignAccess.fromJson(Map<String, dynamic> jsonn) {
    return CampaignAccess(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      role: jsonn['role'] != null ? jsonn['role'].toString() : '',
      sourceGroupId: jsonn['source_group_id'] != null
          ? jsonn['source_group_id'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? campaignId,
    String? userId,
    String? role,
    String? sourceGroupId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (campaignId != null) 'campaign_id': campaignId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (sourceGroupId != null) 'source_group_id': sourceGroupId,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      campaignId: campaignId,
      userId: userId,
      role: role,
      sourceGroupId: sourceGroupId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  CampaignAccess copyWith({
    Object? id = _unset,
    Object? campaignId = _unset,
    Object? userId = _unset,
    Object? role = _unset,
    Object? sourceGroupId = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return CampaignAccess(
      id: id == _unset ? this.id : id as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      userId: userId == _unset ? this.userId : userId as String,
      role: role == _unset ? this.role : role as String,
      sourceGroupId: sourceGroupId == _unset
          ? this.sourceGroupId
          : sourceGroupId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
