// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Characters implements SupadartClass<Characters> {
  final String id;
  final String groupId;
  final String userId;
  final BigInt? dndbeyondCharacterId;
  final String name;
  final String? avatarUrl;
  final int? level;
  final int? armorClass;
  final int? hitPoints;
  final String? race;
  final String? background;
  final Map<String, dynamic> classes;
  final Map<String, dynamic> abilities;
  final Map<String, dynamic> data;
  final Map<String, dynamic> content;
  final Map<String, dynamic> dndbeyondRaw;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Characters({
    required this.id,
    required this.groupId,
    required this.userId,
    this.dndbeyondCharacterId,
    required this.name,
    this.avatarUrl,
    this.level,
    this.armorClass,
    this.hitPoints,
    this.race,
    this.background,
    required this.classes,
    required this.abilities,
    required this.data,
    required this.content,
    required this.dndbeyondRaw,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'characters';
  static String get c_id => 'id';
  static String get c_groupId => 'group_id';
  static String get c_userId => 'user_id';
  static String get c_dndbeyondCharacterId => 'dndbeyond_character_id';
  static String get c_name => 'name';
  static String get c_avatarUrl => 'avatar_url';
  static String get c_level => 'level';
  static String get c_armorClass => 'armor_class';
  static String get c_hitPoints => 'hit_points';
  static String get c_race => 'race';
  static String get c_background => 'background';
  static String get c_classes => 'classes';
  static String get c_abilities => 'abilities';
  static String get c_data => 'data';
  static String get c_content => 'content';
  static String get c_dndbeyondRaw => 'dndbeyond_raw';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Characters> converter(List<Map<String, dynamic>> data) {
    return data.map(Characters.fromJson).toList();
  }

  static Characters converterSingle(Map<String, dynamic> data) {
    return Characters.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? groupId,
    String? userId,
    BigInt? dndbeyondCharacterId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    String? race,
    String? background,
    Map<String, dynamic>? classes,
    Map<String, dynamic>? abilities,
    Map<String, dynamic>? data,
    Map<String, dynamic>? content,
    Map<String, dynamic>? dndbeyondRaw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (dndbeyondCharacterId != null)
        'dndbeyond_character_id': dndbeyondCharacterId.toString(),
      if (name != null) 'name': name,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (level != null) 'level': level,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (race != null) 'race': race,
      if (background != null) 'background': background,
      if (classes != null) 'classes': classes,
      if (abilities != null) 'abilities': abilities,
      if (data != null) 'data': data,
      if (content != null) 'content': content,
      if (dndbeyondRaw != null) 'dndbeyond_raw': dndbeyondRaw,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String groupId,
    required String userId,
    BigInt? dndbeyondCharacterId,
    required String name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    String? race,
    String? background,
    required Map<String, dynamic> classes,
    required Map<String, dynamic> abilities,
    required Map<String, dynamic> data,
    required Map<String, dynamic> content,
    required Map<String, dynamic> dndbeyondRaw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      dndbeyondCharacterId: dndbeyondCharacterId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      race: race,
      background: background,
      classes: classes,
      abilities: abilities,
      data: data,
      content: content,
      dndbeyondRaw: dndbeyondRaw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? groupId,
    String? userId,
    BigInt? dndbeyondCharacterId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    String? race,
    String? background,
    Map<String, dynamic>? classes,
    Map<String, dynamic>? abilities,
    Map<String, dynamic>? data,
    Map<String, dynamic>? content,
    Map<String, dynamic>? dndbeyondRaw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      dndbeyondCharacterId: dndbeyondCharacterId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      race: race,
      background: background,
      classes: classes,
      abilities: abilities,
      data: data,
      content: content,
      dndbeyondRaw: dndbeyondRaw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Characters.fromJson(Map<String, dynamic> jsonn) {
    return Characters(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      dndbeyondCharacterId: jsonn['dndbeyond_character_id'] != null
          ? BigInt.parse(jsonn['dndbeyond_character_id'].toString())
          : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      avatarUrl: jsonn['avatar_url'] != null
          ? jsonn['avatar_url'].toString()
          : null,
      level: jsonn['level'] != null
          ? int.parse(jsonn['level'].toString())
          : null,
      armorClass: jsonn['armor_class'] != null
          ? int.parse(jsonn['armor_class'].toString())
          : null,
      hitPoints: jsonn['hit_points'] != null
          ? int.parse(jsonn['hit_points'].toString())
          : null,
      race: jsonn['race'] != null ? jsonn['race'].toString() : null,
      background: jsonn['background'] != null
          ? jsonn['background'].toString()
          : null,
      classes: jsonn['classes'] != null
          ? jsonn['classes'] as Map<String, dynamic>
          : <String, dynamic>{},
      abilities: jsonn['abilities'] != null
          ? jsonn['abilities'] as Map<String, dynamic>
          : <String, dynamic>{},
      data: jsonn['data'] != null
          ? jsonn['data'] as Map<String, dynamic>
          : <String, dynamic>{},
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : <String, dynamic>{},
      dndbeyondRaw: jsonn['dndbeyond_raw'] != null
          ? jsonn['dndbeyond_raw'] as Map<String, dynamic>
          : <String, dynamic>{},
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? groupId,
    String? userId,
    BigInt? dndbeyondCharacterId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    String? race,
    String? background,
    Map<String, dynamic>? classes,
    Map<String, dynamic>? abilities,
    Map<String, dynamic>? data,
    Map<String, dynamic>? content,
    Map<String, dynamic>? dndbeyondRaw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (dndbeyondCharacterId != null)
        'dndbeyond_character_id': dndbeyondCharacterId,
      if (name != null) 'name': name,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (level != null) 'level': level,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (race != null) 'race': race,
      if (background != null) 'background': background,
      if (classes != null) 'classes': classes,
      if (abilities != null) 'abilities': abilities,
      if (data != null) 'data': data,
      if (content != null) 'content': content,
      if (dndbeyondRaw != null) 'dndbeyond_raw': dndbeyondRaw,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      dndbeyondCharacterId: dndbeyondCharacterId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      race: race,
      background: background,
      classes: classes,
      abilities: abilities,
      data: data,
      content: content,
      dndbeyondRaw: dndbeyondRaw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  Characters copyWith({
    Object? id = _unset,
    Object? groupId = _unset,
    Object? userId = _unset,
    Object? dndbeyondCharacterId = _unset,
    Object? name = _unset,
    Object? avatarUrl = _unset,
    Object? level = _unset,
    Object? armorClass = _unset,
    Object? hitPoints = _unset,
    Object? race = _unset,
    Object? background = _unset,
    Object? classes = _unset,
    Object? abilities = _unset,
    Object? data = _unset,
    Object? content = _unset,
    Object? dndbeyondRaw = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return Characters(
      id: id == _unset ? this.id : id as String,
      groupId: groupId == _unset ? this.groupId : groupId as String,
      userId: userId == _unset ? this.userId : userId as String,
      dndbeyondCharacterId: dndbeyondCharacterId == _unset
          ? this.dndbeyondCharacterId
          : dndbeyondCharacterId as BigInt?,
      name: name == _unset ? this.name : name as String,
      avatarUrl: avatarUrl == _unset ? this.avatarUrl : avatarUrl as String?,
      level: level == _unset ? this.level : level as int?,
      armorClass: armorClass == _unset ? this.armorClass : armorClass as int?,
      hitPoints: hitPoints == _unset ? this.hitPoints : hitPoints as int?,
      race: race == _unset ? this.race : race as String?,
      background: background == _unset
          ? this.background
          : background as String?,
      classes: classes == _unset
          ? this.classes
          : classes as Map<String, dynamic>,
      abilities: abilities == _unset
          ? this.abilities
          : abilities as Map<String, dynamic>,
      data: data == _unset ? this.data : data as Map<String, dynamic>,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>,
      dndbeyondRaw: dndbeyondRaw == _unset
          ? this.dndbeyondRaw
          : dndbeyondRaw as Map<String, dynamic>,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
