// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class ContentScopes implements SupadartClass<ContentScopes> {
  final String id;
  final String scopeType;
  final String campaignId;
  final String? chapterId;
  final String? adventureId;
  final String? sceneId;
  final DateTime createdAt;
  final DateTime updatedAt;

  const ContentScopes({
    required this.id,
    required this.scopeType,
    required this.campaignId,
    this.chapterId,
    this.adventureId,
    this.sceneId,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'content_scopes';
  static String get c_id => 'id';
  static String get c_scopeType => 'scope_type';
  static String get c_campaignId => 'campaign_id';
  static String get c_chapterId => 'chapter_id';
  static String get c_adventureId => 'adventure_id';
  static String get c_sceneId => 'scene_id';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<ContentScopes> converter(List<Map<String, dynamic>> data) {
    return data.map(ContentScopes.fromJson).toList();
  }

  static ContentScopes converterSingle(Map<String, dynamic> data) {
    return ContentScopes.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? scopeType,
    String? campaignId,
    String? chapterId,
    String? adventureId,
    String? sceneId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
      if (chapterId != null) 'chapter_id': chapterId,
      if (adventureId != null) 'adventure_id': adventureId,
      if (sceneId != null) 'scene_id': sceneId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String scopeType,
    required String campaignId,
    String? chapterId,
    String? adventureId,
    String? sceneId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeType: scopeType,
      campaignId: campaignId,
      chapterId: chapterId,
      adventureId: adventureId,
      sceneId: sceneId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? scopeType,
    String? campaignId,
    String? chapterId,
    String? adventureId,
    String? sceneId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeType: scopeType,
      campaignId: campaignId,
      chapterId: chapterId,
      adventureId: adventureId,
      sceneId: sceneId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory ContentScopes.fromJson(Map<String, dynamic> jsonn) {
    return ContentScopes(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      scopeType: jsonn['scope_type'] != null
          ? jsonn['scope_type'].toString()
          : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      chapterId: jsonn['chapter_id'] != null
          ? jsonn['chapter_id'].toString()
          : null,
      adventureId: jsonn['adventure_id'] != null
          ? jsonn['adventure_id'].toString()
          : null,
      sceneId: jsonn['scene_id'] != null ? jsonn['scene_id'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? scopeType,
    String? campaignId,
    String? chapterId,
    String? adventureId,
    String? sceneId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
      if (chapterId != null) 'chapter_id': chapterId,
      if (adventureId != null) 'adventure_id': adventureId,
      if (sceneId != null) 'scene_id': sceneId,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      scopeType: scopeType,
      campaignId: campaignId,
      chapterId: chapterId,
      adventureId: adventureId,
      sceneId: sceneId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  ContentScopes copyWith({
    Object? id = _unset,
    Object? scopeType = _unset,
    Object? campaignId = _unset,
    Object? chapterId = _unset,
    Object? adventureId = _unset,
    Object? sceneId = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return ContentScopes(
      id: id == _unset ? this.id : id as String,
      scopeType: scopeType == _unset ? this.scopeType : scopeType as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      chapterId: chapterId == _unset ? this.chapterId : chapterId as String?,
      adventureId: adventureId == _unset
          ? this.adventureId
          : adventureId as String?,
      sceneId: sceneId == _unset ? this.sceneId : sceneId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
