// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class EncounterCreatures implements SupadartClass<EncounterCreatures> {
  final String id;
  final String encounterId;
  final String creatureId;
  final String campaignId;
  final int quantity;
  final int? initiative;
  final String? notes;
  final DateTime createdAt;
  final DateTime updatedAt;

  const EncounterCreatures({
    required this.id,
    required this.encounterId,
    required this.creatureId,
    required this.campaignId,
    required this.quantity,
    this.initiative,
    this.notes,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'encounter_creatures';
  static String get c_id => 'id';
  static String get c_encounterId => 'encounter_id';
  static String get c_creatureId => 'creature_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_quantity => 'quantity';
  static String get c_initiative => 'initiative';
  static String get c_notes => 'notes';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<EncounterCreatures> converter(List<Map<String, dynamic>> data) {
    return data.map(EncounterCreatures.fromJson).toList();
  }

  static EncounterCreatures converterSingle(Map<String, dynamic> data) {
    return EncounterCreatures.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? encounterId,
    String? creatureId,
    String? campaignId,
    int? quantity,
    int? initiative,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (encounterId != null) 'encounter_id': encounterId,
      if (creatureId != null) 'creature_id': creatureId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (quantity != null) 'quantity': quantity,
      if (initiative != null) 'initiative': initiative,
      if (notes != null) 'notes': notes,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String encounterId,
    required String creatureId,
    required String campaignId,
    int? quantity,
    int? initiative,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      encounterId: encounterId,
      creatureId: creatureId,
      campaignId: campaignId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? encounterId,
    String? creatureId,
    String? campaignId,
    int? quantity,
    int? initiative,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      encounterId: encounterId,
      creatureId: creatureId,
      campaignId: campaignId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory EncounterCreatures.fromJson(Map<String, dynamic> jsonn) {
    return EncounterCreatures(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      encounterId: jsonn['encounter_id'] != null
          ? jsonn['encounter_id'].toString()
          : '',
      creatureId: jsonn['creature_id'] != null
          ? jsonn['creature_id'].toString()
          : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      quantity: jsonn['quantity'] != null
          ? int.parse(jsonn['quantity'].toString())
          : 0,
      initiative: jsonn['initiative'] != null
          ? int.parse(jsonn['initiative'].toString())
          : null,
      notes: jsonn['notes'] != null ? jsonn['notes'].toString() : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? encounterId,
    String? creatureId,
    String? campaignId,
    int? quantity,
    int? initiative,
    String? notes,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (encounterId != null) 'encounter_id': encounterId,
      if (creatureId != null) 'creature_id': creatureId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (quantity != null) 'quantity': quantity,
      if (initiative != null) 'initiative': initiative,
      if (notes != null) 'notes': notes,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      encounterId: encounterId,
      creatureId: creatureId,
      campaignId: campaignId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  EncounterCreatures copyWith({
    Object? id = _unset,
    Object? encounterId = _unset,
    Object? creatureId = _unset,
    Object? campaignId = _unset,
    Object? quantity = _unset,
    Object? initiative = _unset,
    Object? notes = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return EncounterCreatures(
      id: id == _unset ? this.id : id as String,
      encounterId: encounterId == _unset
          ? this.encounterId
          : encounterId as String,
      creatureId: creatureId == _unset ? this.creatureId : creatureId as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      quantity: quantity == _unset ? this.quantity : quantity as int,
      initiative: initiative == _unset ? this.initiative : initiative as int?,
      notes: notes == _unset ? this.notes : notes as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
