// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class GroupMembers implements SupadartClass<GroupMembers> {
  final String id;
  final String groupId;
  final String userId;
  final String role;
  final DateTime createdAt;
  final DateTime updatedAt;

  const GroupMembers({
    required this.id,
    required this.groupId,
    required this.userId,
    required this.role,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'group_members';
  static String get c_id => 'id';
  static String get c_groupId => 'group_id';
  static String get c_userId => 'user_id';
  static String get c_role => 'role';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<GroupMembers> converter(List<Map<String, dynamic>> data) {
    return data.map(GroupMembers.fromJson).toList();
  }

  static GroupMembers converterSingle(Map<String, dynamic> data) {
    return GroupMembers.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? groupId,
    String? userId,
    String? role,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String groupId,
    required String userId,
    required String role,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      role: role,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? groupId,
    String? userId,
    String? role,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      role: role,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory GroupMembers.fromJson(Map<String, dynamic> jsonn) {
    return GroupMembers(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : '',
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      role: jsonn['role'] != null ? jsonn['role'].toString() : '',
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? groupId,
    String? userId,
    String? role,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (role != null) 'role': role,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      role: role,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  GroupMembers copyWith({
    Object? id = _unset,
    Object? groupId = _unset,
    Object? userId = _unset,
    Object? role = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return GroupMembers(
      id: id == _unset ? this.id : id as String,
      groupId: groupId == _unset ? this.groupId : groupId as String,
      userId: userId == _unset ? this.userId : userId as String,
      role: role == _unset ? this.role : role as String,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
