// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class Organisations implements SupadartClass<Organisations> {
  final String id;
  final String scopeId;
  final String campaignId;
  final String name;
  final String type;
  final String? description;
  final Map<String, dynamic> content;
  final String? hqLocationId;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Organisations({
    required this.id,
    required this.scopeId,
    required this.campaignId,
    required this.name,
    required this.type,
    this.description,
    required this.content,
    this.hqLocationId,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'organisations';
  static String get c_id => 'id';
  static String get c_scopeId => 'scope_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_name => 'name';
  static String get c_type => 'type';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_hqLocationId => 'hq_location_id';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Organisations> converter(List<Map<String, dynamic>> data) {
    return data.map(Organisations.fromJson).toList();
  }

  static Organisations converterSingle(Map<String, dynamic> data) {
    return Organisations.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? scopeId,
    String? campaignId,
    String? name,
    String? type,
    String? description,
    Map<String, dynamic>? content,
    String? hqLocationId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (name != null) 'name': name,
      if (type != null) 'type': type,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (hqLocationId != null) 'hq_location_id': hqLocationId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String scopeId,
    required String campaignId,
    required String name,
    required String type,
    String? description,
    required Map<String, dynamic> content,
    String? hqLocationId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      name: name,
      type: type,
      description: description,
      content: content,
      hqLocationId: hqLocationId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? scopeId,
    String? campaignId,
    String? name,
    String? type,
    String? description,
    Map<String, dynamic>? content,
    String? hqLocationId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      name: name,
      type: type,
      description: description,
      content: content,
      hqLocationId: hqLocationId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Organisations.fromJson(Map<String, dynamic> jsonn) {
    return Organisations(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      name: jsonn['name'] != null ? jsonn['name'].toString() : '',
      type: jsonn['type'] != null ? jsonn['type'].toString() : '',
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : <String, dynamic>{},
      hqLocationId: jsonn['hq_location_id'] != null
          ? jsonn['hq_location_id'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? scopeId,
    String? campaignId,
    String? name,
    String? type,
    String? description,
    Map<String, dynamic>? content,
    String? hqLocationId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (name != null) 'name': name,
      if (type != null) 'type': type,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (hqLocationId != null) 'hq_location_id': hqLocationId,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      name: name,
      type: type,
      description: description,
      content: content,
      hqLocationId: hqLocationId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  Organisations copyWith({
    Object? id = _unset,
    Object? scopeId = _unset,
    Object? campaignId = _unset,
    Object? name = _unset,
    Object? type = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? hqLocationId = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return Organisations(
      id: id == _unset ? this.id : id as String,
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      name: name == _unset ? this.name : name as String,
      type: type == _unset ? this.type : type as String,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>,
      hqLocationId: hqLocationId == _unset
          ? this.hqLocationId
          : hqLocationId as String?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
