// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class PlayingCampaigns implements SupadartClass<PlayingCampaigns> {
  final String groupId;
  final String campaignId;
  final DateTime createdAt;
  final DateTime updatedAt;

  const PlayingCampaigns({
    required this.groupId,
    required this.campaignId,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'playing_campaigns';
  static String get c_groupId => 'group_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<PlayingCampaigns> converter(List<Map<String, dynamic>> data) {
    return data.map(PlayingCampaigns.fromJson).toList();
  }

  static PlayingCampaigns converterSingle(Map<String, dynamic> data) {
    return PlayingCampaigns.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? groupId,
    String? campaignId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (groupId != null) 'group_id': groupId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? groupId,
    required String campaignId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      groupId: groupId,
      campaignId: campaignId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? groupId,
    String? campaignId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      groupId: groupId,
      campaignId: campaignId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory PlayingCampaigns.fromJson(Map<String, dynamic> jsonn) {
    return PlayingCampaigns(
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : '',
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : '',
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? groupId,
    String? campaignId,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (groupId != null) 'group_id': groupId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      groupId: groupId,
      campaignId: campaignId,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  PlayingCampaigns copyWith({
    Object? groupId = _unset,
    Object? campaignId = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return PlayingCampaigns(
      groupId: groupId == _unset ? this.groupId : groupId as String,
      campaignId: campaignId == _unset ? this.campaignId : campaignId as String,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
