// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class SessionLogs implements SupadartClass<SessionLogs> {
  final String id;
  final String groupId;
  final int? sessionNumber;
  final DateTime? sessionDate;
  final String? title;
  final Map<String, dynamic> content;
  final DateTime createdAt;
  final DateTime updatedAt;

  const SessionLogs({
    required this.id,
    required this.groupId,
    this.sessionNumber,
    this.sessionDate,
    this.title,
    required this.content,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'session_logs';
  static String get c_id => 'id';
  static String get c_groupId => 'group_id';
  static String get c_sessionNumber => 'session_number';
  static String get c_sessionDate => 'session_date';
  static String get c_title => 'title';
  static String get c_content => 'content';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<SessionLogs> converter(List<Map<String, dynamic>> data) {
    return data.map(SessionLogs.fromJson).toList();
  }

  static SessionLogs converterSingle(Map<String, dynamic> data) {
    return SessionLogs.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? groupId,
    int? sessionNumber,
    DateTime? sessionDate,
    String? title,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (sessionNumber != null) 'session_number': sessionNumber,
      if (sessionDate != null) 'session_date': sessionDate.toIso8601String(),
      if (title != null) 'title': title,
      if (content != null) 'content': content,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String groupId,
    int? sessionNumber,
    DateTime? sessionDate,
    String? title,
    required Map<String, dynamic> content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      sessionNumber: sessionNumber,
      sessionDate: sessionDate,
      title: title,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? groupId,
    int? sessionNumber,
    DateTime? sessionDate,
    String? title,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      sessionNumber: sessionNumber,
      sessionDate: sessionDate,
      title: title,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory SessionLogs.fromJson(Map<String, dynamic> jsonn) {
    return SessionLogs(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : '',
      sessionNumber: jsonn['session_number'] != null
          ? int.parse(jsonn['session_number'].toString())
          : null,
      sessionDate: jsonn['session_date'] != null
          ? DateTime.parse(jsonn['session_date'].toString())
          : null,
      title: jsonn['title'] != null ? jsonn['title'].toString() : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : <String, dynamic>{},
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  static Object New({
    String? id,
    String? groupId,
    int? sessionNumber,
    DateTime? sessionDate,
    String? title,
    Map<String, dynamic>? content,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (sessionNumber != null) 'session_number': sessionNumber,
      if (sessionDate != null) 'session_date': sessionDate,
      if (title != null) 'title': title,
      if (content != null) 'content': content,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      groupId: groupId,
      sessionNumber: sessionNumber,
      sessionDate: sessionDate,
      title: title,
      content: content,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  SessionLogs copyWith({
    Object? id = _unset,
    Object? groupId = _unset,
    Object? sessionNumber = _unset,
    Object? sessionDate = _unset,
    Object? title = _unset,
    Object? content = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return SessionLogs(
      id: id == _unset ? this.id : id as String,
      groupId: groupId == _unset ? this.groupId : groupId as String,
      sessionNumber: sessionNumber == _unset
          ? this.sessionNumber
          : sessionNumber as int?,
      sessionDate: sessionDate == _unset
          ? this.sessionDate
          : sessionDate as DateTime?,
      title: title == _unset ? this.title : title as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime,
    );
  }
}
