// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison,prefer_null_aware_operators

// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

// SDK
import 'package:supabase_flutter/supabase_flutter.dart';

// No geobase needed
// No Intl package needed
// No Dart Convert needed
// No JSONB Model imports needed
// Supadart Class
abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }

  static converter(List<Map<String, dynamic>> data) {
    throw UnimplementedError();
  }

  static converterSingle(Map<String, dynamic> data) {
    throw UnimplementedError();
  }
}

// Supabase Client Extension
extension SupadartClient on SupabaseClient {
  SupabaseQueryBuilder get v_encounter_with_path =>
      from('v_encounter_with_path');
  SupabaseQueryBuilder get v_campaign_creatures => from('v_campaign_creatures');
  SupabaseQueryBuilder get v_character_quick => from('v_character_quick');
  SupabaseQueryBuilder get groups => from('groups');
  SupabaseQueryBuilder get organisations => from('organisations');
  SupabaseQueryBuilder get v_group_dashboard => from('v_group_dashboard');
  SupabaseQueryBuilder get adventures => from('adventures');
  SupabaseQueryBuilder get encounter_creatures => from('encounter_creatures');
  SupabaseQueryBuilder get campaign_access => from('campaign_access');
  SupabaseQueryBuilder get session_logs => from('session_logs');
  SupabaseQueryBuilder get v_scope_path => from('v_scope_path');
  SupabaseQueryBuilder get v_scope_campaign => from('v_scope_campaign');
  SupabaseQueryBuilder get chapters => from('chapters');
  SupabaseQueryBuilder get v_campaign_outline => from('v_campaign_outline');
  SupabaseQueryBuilder get locations => from('locations');
  SupabaseQueryBuilder get scenes => from('scenes');
  SupabaseQueryBuilder get playing_campaigns => from('playing_campaigns');
  SupabaseQueryBuilder get v_campaign_items => from('v_campaign_items');
  SupabaseQueryBuilder get v_item_with_path => from('v_item_with_path');
  SupabaseQueryBuilder get v_campaign_encounters =>
      from('v_campaign_encounters');
  SupabaseQueryBuilder get v_encounter_expanded_with_path =>
      from('v_encounter_expanded_with_path');
  SupabaseQueryBuilder get campaigns => from('campaigns');
  SupabaseQueryBuilder get v_organisation_with_path =>
      from('v_organisation_with_path');
  SupabaseQueryBuilder get characters => from('characters');
  SupabaseQueryBuilder get v_creature_with_path => from('v_creature_with_path');
  SupabaseQueryBuilder get v_campaign_locations => from('v_campaign_locations');
  SupabaseQueryBuilder get v_location_with_path => from('v_location_with_path');
  SupabaseQueryBuilder get encounters => from('encounters');
  SupabaseQueryBuilder get maps => from('maps');
  SupabaseQueryBuilder get creatures => from('creatures');
  SupabaseQueryBuilder get group_members => from('group_members');
  SupabaseQueryBuilder get v_campaign_organisations =>
      from('v_campaign_organisations');
  SupabaseQueryBuilder get items => from('items');
  SupabaseQueryBuilder get content_scopes => from('content_scopes');
}

// Supabase Storage Client Extension
extension SupadartStorageClient on SupabaseStorageClient {}

// Enums
enum CREATURE_KIND { npc, creature }

enum ORGANISATION_TYPE { faction, family, guild, cult, church, company, other }

enum SCOPE_TYPE { campaign, chapter, adventure, scene }

// Utils
