// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class UserPreferences implements SupadartClass<UserPreferences> {
  final String userId;
  final String? appLanguage;

  const UserPreferences({required this.userId, this.appLanguage});

  static String get table_name => 'user_preferences';
  static String get c_userId => 'user_id';
  static String get c_appLanguage => 'app_language';

  static List<UserPreferences> converter(List<Map<String, dynamic>> data) {
    return data.map(UserPreferences.fromJson).toList();
  }

  static UserPreferences converterSingle(Map<String, dynamic> data) {
    return UserPreferences.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? userId,
    String? appLanguage,
  }) {
    return {
      if (userId != null) 'user_id': userId,
      if (appLanguage != null) 'app_language': appLanguage,
    };
  }

  static Map<String, dynamic> insert({String? userId, String? appLanguage}) {
    return _generateMap(userId: userId, appLanguage: appLanguage);
  }

  static Map<String, dynamic> update({String? userId, String? appLanguage}) {
    return _generateMap(userId: userId, appLanguage: appLanguage);
  }

  factory UserPreferences.fromJson(Map<String, dynamic> jsonn) {
    return UserPreferences(
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : '',
      appLanguage: jsonn['app_language'] != null
          ? jsonn['app_language'].toString()
          : null,
    );
  }

  static Object New({String? userId, String? appLanguage}) {
    return {
      if (userId != null) 'user_id': userId,
      if (appLanguage != null) 'app_language': appLanguage,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(userId: userId, appLanguage: appLanguage);
  }

  static const _unset = Object();
  UserPreferences copyWith({
    Object? userId = _unset,
    Object? appLanguage = _unset,
  }) {
    return UserPreferences(
      userId: userId == _unset ? this.userId : userId as String,
      appLanguage: appLanguage == _unset
          ? this.appLanguage
          : appLanguage as String?,
    );
  }
}
