// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VCampaignCreatures implements SupadartClass<VCampaignCreatures> {
  final String? id;
  final String? scopeId;
  final String? campaignId;
  final String? organisationId;
  final String? name;
  final String? kind;
  final String? source;
  final String? size;
  final String? creatureType;
  final String? subtype;
  final String? alignment;
  final num? challengeRatingDecimal;
  final String? challengeRatingText;
  final int? experiencePoints;
  final int? armorClass;
  final int? hitPoints;
  final String? hitDice;
  final Map<String, dynamic>? speed;
  final Map<String, dynamic>? abilityScores;
  final Map<String, dynamic>? savingThrows;
  final Map<String, dynamic>? skills;
  final Map<String, dynamic>? senses;
  final Map<String, dynamic>? languages;
  final Map<String, dynamic>? damageResistances;
  final Map<String, dynamic>? damageImmunities;
  final Map<String, dynamic>? conditionImmunities;
  final Map<String, dynamic>? traits;
  final Map<String, dynamic>? actions;
  final Map<String, dynamic>? reactions;
  final Map<String, dynamic>? legendaryActions;
  final Map<String, dynamic>? spellcasting;
  final String? description;
  final Map<String, dynamic>? content;
  final Map<String, dynamic>? raw;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  const VCampaignCreatures({
    this.id,
    this.scopeId,
    this.campaignId,
    this.organisationId,
    this.name,
    this.kind,
    this.source,
    this.size,
    this.creatureType,
    this.subtype,
    this.alignment,
    this.challengeRatingDecimal,
    this.challengeRatingText,
    this.experiencePoints,
    this.armorClass,
    this.hitPoints,
    this.hitDice,
    this.speed,
    this.abilityScores,
    this.savingThrows,
    this.skills,
    this.senses,
    this.languages,
    this.damageResistances,
    this.damageImmunities,
    this.conditionImmunities,
    this.traits,
    this.actions,
    this.reactions,
    this.legendaryActions,
    this.spellcasting,
    this.description,
    this.content,
    this.raw,
    this.createdAt,
    this.updatedAt,
  });

  static String get table_name => 'v_campaign_creatures';
  static String get c_id => 'id';
  static String get c_scopeId => 'scope_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_organisationId => 'organisation_id';
  static String get c_name => 'name';
  static String get c_kind => 'kind';
  static String get c_source => 'source';
  static String get c_size => 'size';
  static String get c_creatureType => 'creature_type';
  static String get c_subtype => 'subtype';
  static String get c_alignment => 'alignment';
  static String get c_challengeRatingDecimal => 'challenge_rating_decimal';
  static String get c_challengeRatingText => 'challenge_rating_text';
  static String get c_experiencePoints => 'experience_points';
  static String get c_armorClass => 'armor_class';
  static String get c_hitPoints => 'hit_points';
  static String get c_hitDice => 'hit_dice';
  static String get c_speed => 'speed';
  static String get c_abilityScores => 'ability_scores';
  static String get c_savingThrows => 'saving_throws';
  static String get c_skills => 'skills';
  static String get c_senses => 'senses';
  static String get c_languages => 'languages';
  static String get c_damageResistances => 'damage_resistances';
  static String get c_damageImmunities => 'damage_immunities';
  static String get c_conditionImmunities => 'condition_immunities';
  static String get c_traits => 'traits';
  static String get c_actions => 'actions';
  static String get c_reactions => 'reactions';
  static String get c_legendaryActions => 'legendary_actions';
  static String get c_spellcasting => 'spellcasting';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_raw => 'raw';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<VCampaignCreatures> converter(List<Map<String, dynamic>> data) {
    return data.map(VCampaignCreatures.fromJson).toList();
  }

  static VCampaignCreatures converterSingle(Map<String, dynamic> data) {
    return VCampaignCreatures.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? scopeId,
    String? campaignId,
    String? organisationId,
    String? name,
    String? kind,
    String? source,
    String? size,
    String? creatureType,
    String? subtype,
    String? alignment,
    num? challengeRatingDecimal,
    String? challengeRatingText,
    int? experiencePoints,
    int? armorClass,
    int? hitPoints,
    String? hitDice,
    Map<String, dynamic>? speed,
    Map<String, dynamic>? abilityScores,
    Map<String, dynamic>? savingThrows,
    Map<String, dynamic>? skills,
    Map<String, dynamic>? senses,
    Map<String, dynamic>? languages,
    Map<String, dynamic>? damageResistances,
    Map<String, dynamic>? damageImmunities,
    Map<String, dynamic>? conditionImmunities,
    Map<String, dynamic>? traits,
    Map<String, dynamic>? actions,
    Map<String, dynamic>? reactions,
    Map<String, dynamic>? legendaryActions,
    Map<String, dynamic>? spellcasting,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? raw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (organisationId != null) 'organisation_id': organisationId,
      if (name != null) 'name': name,
      if (kind != null) 'kind': kind,
      if (source != null) 'source': source,
      if (size != null) 'size': size,
      if (creatureType != null) 'creature_type': creatureType,
      if (subtype != null) 'subtype': subtype,
      if (alignment != null) 'alignment': alignment,
      if (challengeRatingDecimal != null)
        'challenge_rating_decimal': challengeRatingDecimal.toString(),
      if (challengeRatingText != null)
        'challenge_rating_text': challengeRatingText,
      if (experiencePoints != null) 'experience_points': experiencePoints,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (hitDice != null) 'hit_dice': hitDice,
      if (speed != null) 'speed': speed,
      if (abilityScores != null) 'ability_scores': abilityScores,
      if (savingThrows != null) 'saving_throws': savingThrows,
      if (skills != null) 'skills': skills,
      if (senses != null) 'senses': senses,
      if (languages != null) 'languages': languages,
      if (damageResistances != null) 'damage_resistances': damageResistances,
      if (damageImmunities != null) 'damage_immunities': damageImmunities,
      if (conditionImmunities != null)
        'condition_immunities': conditionImmunities,
      if (traits != null) 'traits': traits,
      if (actions != null) 'actions': actions,
      if (reactions != null) 'reactions': reactions,
      if (legendaryActions != null) 'legendary_actions': legendaryActions,
      if (spellcasting != null) 'spellcasting': spellcasting,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (raw != null) 'raw': raw,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? scopeId,
    String? campaignId,
    String? organisationId,
    String? name,
    String? kind,
    String? source,
    String? size,
    String? creatureType,
    String? subtype,
    String? alignment,
    num? challengeRatingDecimal,
    String? challengeRatingText,
    int? experiencePoints,
    int? armorClass,
    int? hitPoints,
    String? hitDice,
    Map<String, dynamic>? speed,
    Map<String, dynamic>? abilityScores,
    Map<String, dynamic>? savingThrows,
    Map<String, dynamic>? skills,
    Map<String, dynamic>? senses,
    Map<String, dynamic>? languages,
    Map<String, dynamic>? damageResistances,
    Map<String, dynamic>? damageImmunities,
    Map<String, dynamic>? conditionImmunities,
    Map<String, dynamic>? traits,
    Map<String, dynamic>? actions,
    Map<String, dynamic>? reactions,
    Map<String, dynamic>? legendaryActions,
    Map<String, dynamic>? spellcasting,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? raw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      organisationId: organisationId,
      name: name,
      kind: kind,
      source: source,
      size: size,
      creatureType: creatureType,
      subtype: subtype,
      alignment: alignment,
      challengeRatingDecimal: challengeRatingDecimal,
      challengeRatingText: challengeRatingText,
      experiencePoints: experiencePoints,
      armorClass: armorClass,
      hitPoints: hitPoints,
      hitDice: hitDice,
      speed: speed,
      abilityScores: abilityScores,
      savingThrows: savingThrows,
      skills: skills,
      senses: senses,
      languages: languages,
      damageResistances: damageResistances,
      damageImmunities: damageImmunities,
      conditionImmunities: conditionImmunities,
      traits: traits,
      actions: actions,
      reactions: reactions,
      legendaryActions: legendaryActions,
      spellcasting: spellcasting,
      description: description,
      content: content,
      raw: raw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? scopeId,
    String? campaignId,
    String? organisationId,
    String? name,
    String? kind,
    String? source,
    String? size,
    String? creatureType,
    String? subtype,
    String? alignment,
    num? challengeRatingDecimal,
    String? challengeRatingText,
    int? experiencePoints,
    int? armorClass,
    int? hitPoints,
    String? hitDice,
    Map<String, dynamic>? speed,
    Map<String, dynamic>? abilityScores,
    Map<String, dynamic>? savingThrows,
    Map<String, dynamic>? skills,
    Map<String, dynamic>? senses,
    Map<String, dynamic>? languages,
    Map<String, dynamic>? damageResistances,
    Map<String, dynamic>? damageImmunities,
    Map<String, dynamic>? conditionImmunities,
    Map<String, dynamic>? traits,
    Map<String, dynamic>? actions,
    Map<String, dynamic>? reactions,
    Map<String, dynamic>? legendaryActions,
    Map<String, dynamic>? spellcasting,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? raw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      organisationId: organisationId,
      name: name,
      kind: kind,
      source: source,
      size: size,
      creatureType: creatureType,
      subtype: subtype,
      alignment: alignment,
      challengeRatingDecimal: challengeRatingDecimal,
      challengeRatingText: challengeRatingText,
      experiencePoints: experiencePoints,
      armorClass: armorClass,
      hitPoints: hitPoints,
      hitDice: hitDice,
      speed: speed,
      abilityScores: abilityScores,
      savingThrows: savingThrows,
      skills: skills,
      senses: senses,
      languages: languages,
      damageResistances: damageResistances,
      damageImmunities: damageImmunities,
      conditionImmunities: conditionImmunities,
      traits: traits,
      actions: actions,
      reactions: reactions,
      legendaryActions: legendaryActions,
      spellcasting: spellcasting,
      description: description,
      content: content,
      raw: raw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory VCampaignCreatures.fromJson(Map<String, dynamic> jsonn) {
    return VCampaignCreatures(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : null,
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : null,
      organisationId: jsonn['organisation_id'] != null
          ? jsonn['organisation_id'].toString()
          : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      kind: jsonn['kind'] != null ? jsonn['kind'].toString() : null,
      source: jsonn['source'] != null ? jsonn['source'].toString() : null,
      size: jsonn['size'] != null ? jsonn['size'].toString() : null,
      creatureType: jsonn['creature_type'] != null
          ? jsonn['creature_type'].toString()
          : null,
      subtype: jsonn['subtype'] != null ? jsonn['subtype'].toString() : null,
      alignment: jsonn['alignment'] != null
          ? jsonn['alignment'].toString()
          : null,
      challengeRatingDecimal: jsonn['challenge_rating_decimal'] != null
          ? num.parse(jsonn['challenge_rating_decimal'].toString())
          : null,
      challengeRatingText: jsonn['challenge_rating_text'] != null
          ? jsonn['challenge_rating_text'].toString()
          : null,
      experiencePoints: jsonn['experience_points'] != null
          ? int.parse(jsonn['experience_points'].toString())
          : null,
      armorClass: jsonn['armor_class'] != null
          ? int.parse(jsonn['armor_class'].toString())
          : null,
      hitPoints: jsonn['hit_points'] != null
          ? int.parse(jsonn['hit_points'].toString())
          : null,
      hitDice: jsonn['hit_dice'] != null ? jsonn['hit_dice'].toString() : null,
      speed: jsonn['speed'] != null
          ? jsonn['speed'] as Map<String, dynamic>
          : null,
      abilityScores: jsonn['ability_scores'] != null
          ? jsonn['ability_scores'] as Map<String, dynamic>
          : null,
      savingThrows: jsonn['saving_throws'] != null
          ? jsonn['saving_throws'] as Map<String, dynamic>
          : null,
      skills: jsonn['skills'] != null
          ? jsonn['skills'] as Map<String, dynamic>
          : null,
      senses: jsonn['senses'] != null
          ? jsonn['senses'] as Map<String, dynamic>
          : null,
      languages: jsonn['languages'] != null
          ? jsonn['languages'] as Map<String, dynamic>
          : null,
      damageResistances: jsonn['damage_resistances'] != null
          ? jsonn['damage_resistances'] as Map<String, dynamic>
          : null,
      damageImmunities: jsonn['damage_immunities'] != null
          ? jsonn['damage_immunities'] as Map<String, dynamic>
          : null,
      conditionImmunities: jsonn['condition_immunities'] != null
          ? jsonn['condition_immunities'] as Map<String, dynamic>
          : null,
      traits: jsonn['traits'] != null
          ? jsonn['traits'] as Map<String, dynamic>
          : null,
      actions: jsonn['actions'] != null
          ? jsonn['actions'] as Map<String, dynamic>
          : null,
      reactions: jsonn['reactions'] != null
          ? jsonn['reactions'] as Map<String, dynamic>
          : null,
      legendaryActions: jsonn['legendary_actions'] != null
          ? jsonn['legendary_actions'] as Map<String, dynamic>
          : null,
      spellcasting: jsonn['spellcasting'] != null
          ? jsonn['spellcasting'] as Map<String, dynamic>
          : null,
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : null,
      raw: jsonn['raw'] != null ? jsonn['raw'] as Map<String, dynamic> : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? scopeId,
    String? campaignId,
    String? organisationId,
    String? name,
    String? kind,
    String? source,
    String? size,
    String? creatureType,
    String? subtype,
    String? alignment,
    num? challengeRatingDecimal,
    String? challengeRatingText,
    int? experiencePoints,
    int? armorClass,
    int? hitPoints,
    String? hitDice,
    Map<String, dynamic>? speed,
    Map<String, dynamic>? abilityScores,
    Map<String, dynamic>? savingThrows,
    Map<String, dynamic>? skills,
    Map<String, dynamic>? senses,
    Map<String, dynamic>? languages,
    Map<String, dynamic>? damageResistances,
    Map<String, dynamic>? damageImmunities,
    Map<String, dynamic>? conditionImmunities,
    Map<String, dynamic>? traits,
    Map<String, dynamic>? actions,
    Map<String, dynamic>? reactions,
    Map<String, dynamic>? legendaryActions,
    Map<String, dynamic>? spellcasting,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? raw,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (organisationId != null) 'organisation_id': organisationId,
      if (name != null) 'name': name,
      if (kind != null) 'kind': kind,
      if (source != null) 'source': source,
      if (size != null) 'size': size,
      if (creatureType != null) 'creature_type': creatureType,
      if (subtype != null) 'subtype': subtype,
      if (alignment != null) 'alignment': alignment,
      if (challengeRatingDecimal != null)
        'challenge_rating_decimal': challengeRatingDecimal,
      if (challengeRatingText != null)
        'challenge_rating_text': challengeRatingText,
      if (experiencePoints != null) 'experience_points': experiencePoints,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (hitDice != null) 'hit_dice': hitDice,
      if (speed != null) 'speed': speed,
      if (abilityScores != null) 'ability_scores': abilityScores,
      if (savingThrows != null) 'saving_throws': savingThrows,
      if (skills != null) 'skills': skills,
      if (senses != null) 'senses': senses,
      if (languages != null) 'languages': languages,
      if (damageResistances != null) 'damage_resistances': damageResistances,
      if (damageImmunities != null) 'damage_immunities': damageImmunities,
      if (conditionImmunities != null)
        'condition_immunities': conditionImmunities,
      if (traits != null) 'traits': traits,
      if (actions != null) 'actions': actions,
      if (reactions != null) 'reactions': reactions,
      if (legendaryActions != null) 'legendary_actions': legendaryActions,
      if (spellcasting != null) 'spellcasting': spellcasting,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (raw != null) 'raw': raw,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      organisationId: organisationId,
      name: name,
      kind: kind,
      source: source,
      size: size,
      creatureType: creatureType,
      subtype: subtype,
      alignment: alignment,
      challengeRatingDecimal: challengeRatingDecimal,
      challengeRatingText: challengeRatingText,
      experiencePoints: experiencePoints,
      armorClass: armorClass,
      hitPoints: hitPoints,
      hitDice: hitDice,
      speed: speed,
      abilityScores: abilityScores,
      savingThrows: savingThrows,
      skills: skills,
      senses: senses,
      languages: languages,
      damageResistances: damageResistances,
      damageImmunities: damageImmunities,
      conditionImmunities: conditionImmunities,
      traits: traits,
      actions: actions,
      reactions: reactions,
      legendaryActions: legendaryActions,
      spellcasting: spellcasting,
      description: description,
      content: content,
      raw: raw,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  VCampaignCreatures copyWith({
    Object? id = _unset,
    Object? scopeId = _unset,
    Object? campaignId = _unset,
    Object? organisationId = _unset,
    Object? name = _unset,
    Object? kind = _unset,
    Object? source = _unset,
    Object? size = _unset,
    Object? creatureType = _unset,
    Object? subtype = _unset,
    Object? alignment = _unset,
    Object? challengeRatingDecimal = _unset,
    Object? challengeRatingText = _unset,
    Object? experiencePoints = _unset,
    Object? armorClass = _unset,
    Object? hitPoints = _unset,
    Object? hitDice = _unset,
    Object? speed = _unset,
    Object? abilityScores = _unset,
    Object? savingThrows = _unset,
    Object? skills = _unset,
    Object? senses = _unset,
    Object? languages = _unset,
    Object? damageResistances = _unset,
    Object? damageImmunities = _unset,
    Object? conditionImmunities = _unset,
    Object? traits = _unset,
    Object? actions = _unset,
    Object? reactions = _unset,
    Object? legendaryActions = _unset,
    Object? spellcasting = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? raw = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
  }) {
    return VCampaignCreatures(
      id: id == _unset ? this.id : id as String?,
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String?,
      campaignId: campaignId == _unset
          ? this.campaignId
          : campaignId as String?,
      organisationId: organisationId == _unset
          ? this.organisationId
          : organisationId as String?,
      name: name == _unset ? this.name : name as String?,
      kind: kind == _unset ? this.kind : kind as String?,
      source: source == _unset ? this.source : source as String?,
      size: size == _unset ? this.size : size as String?,
      creatureType: creatureType == _unset
          ? this.creatureType
          : creatureType as String?,
      subtype: subtype == _unset ? this.subtype : subtype as String?,
      alignment: alignment == _unset ? this.alignment : alignment as String?,
      challengeRatingDecimal: challengeRatingDecimal == _unset
          ? this.challengeRatingDecimal
          : challengeRatingDecimal as num?,
      challengeRatingText: challengeRatingText == _unset
          ? this.challengeRatingText
          : challengeRatingText as String?,
      experiencePoints: experiencePoints == _unset
          ? this.experiencePoints
          : experiencePoints as int?,
      armorClass: armorClass == _unset ? this.armorClass : armorClass as int?,
      hitPoints: hitPoints == _unset ? this.hitPoints : hitPoints as int?,
      hitDice: hitDice == _unset ? this.hitDice : hitDice as String?,
      speed: speed == _unset ? this.speed : speed as Map<String, dynamic>?,
      abilityScores: abilityScores == _unset
          ? this.abilityScores
          : abilityScores as Map<String, dynamic>?,
      savingThrows: savingThrows == _unset
          ? this.savingThrows
          : savingThrows as Map<String, dynamic>?,
      skills: skills == _unset ? this.skills : skills as Map<String, dynamic>?,
      senses: senses == _unset ? this.senses : senses as Map<String, dynamic>?,
      languages: languages == _unset
          ? this.languages
          : languages as Map<String, dynamic>?,
      damageResistances: damageResistances == _unset
          ? this.damageResistances
          : damageResistances as Map<String, dynamic>?,
      damageImmunities: damageImmunities == _unset
          ? this.damageImmunities
          : damageImmunities as Map<String, dynamic>?,
      conditionImmunities: conditionImmunities == _unset
          ? this.conditionImmunities
          : conditionImmunities as Map<String, dynamic>?,
      traits: traits == _unset ? this.traits : traits as Map<String, dynamic>?,
      actions: actions == _unset
          ? this.actions
          : actions as Map<String, dynamic>?,
      reactions: reactions == _unset
          ? this.reactions
          : reactions as Map<String, dynamic>?,
      legendaryActions: legendaryActions == _unset
          ? this.legendaryActions
          : legendaryActions as Map<String, dynamic>?,
      spellcasting: spellcasting == _unset
          ? this.spellcasting
          : spellcasting as Map<String, dynamic>?,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>?,
      raw: raw == _unset ? this.raw : raw as Map<String, dynamic>?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
    );
  }
}
