// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VCharacterQuick implements SupadartClass<VCharacterQuick> {
  final String? id;
  final String? groupId;
  final String? userId;
  final String? name;
  final String? avatarUrl;
  final int? level;
  final int? armorClass;
  final int? hitPoints;
  final Map<String, dynamic>? abilities;
  final String? race;
  final Map<String, dynamic>? classes;
  final BigInt? dndbeyondCharacterId;
  final DateTime? updatedAt;

  const VCharacterQuick({
    this.id,
    this.groupId,
    this.userId,
    this.name,
    this.avatarUrl,
    this.level,
    this.armorClass,
    this.hitPoints,
    this.abilities,
    this.race,
    this.classes,
    this.dndbeyondCharacterId,
    this.updatedAt,
  });

  static String get table_name => 'v_character_quick';
  static String get c_id => 'id';
  static String get c_groupId => 'group_id';
  static String get c_userId => 'user_id';
  static String get c_name => 'name';
  static String get c_avatarUrl => 'avatar_url';
  static String get c_level => 'level';
  static String get c_armorClass => 'armor_class';
  static String get c_hitPoints => 'hit_points';
  static String get c_abilities => 'abilities';
  static String get c_race => 'race';
  static String get c_classes => 'classes';
  static String get c_dndbeyondCharacterId => 'dndbeyond_character_id';
  static String get c_updatedAt => 'updated_at';

  static List<VCharacterQuick> converter(List<Map<String, dynamic>> data) {
    return data.map(VCharacterQuick.fromJson).toList();
  }

  static VCharacterQuick converterSingle(Map<String, dynamic> data) {
    return VCharacterQuick.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? groupId,
    String? userId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    Map<String, dynamic>? abilities,
    String? race,
    Map<String, dynamic>? classes,
    BigInt? dndbeyondCharacterId,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (name != null) 'name': name,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (level != null) 'level': level,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (abilities != null) 'abilities': abilities,
      if (race != null) 'race': race,
      if (classes != null) 'classes': classes,
      if (dndbeyondCharacterId != null)
        'dndbeyond_character_id': dndbeyondCharacterId.toString(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? groupId,
    String? userId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    Map<String, dynamic>? abilities,
    String? race,
    Map<String, dynamic>? classes,
    BigInt? dndbeyondCharacterId,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      abilities: abilities,
      race: race,
      classes: classes,
      dndbeyondCharacterId: dndbeyondCharacterId,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? groupId,
    String? userId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    Map<String, dynamic>? abilities,
    String? race,
    Map<String, dynamic>? classes,
    BigInt? dndbeyondCharacterId,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      abilities: abilities,
      race: race,
      classes: classes,
      dndbeyondCharacterId: dndbeyondCharacterId,
      updatedAt: updatedAt,
    );
  }

  factory VCharacterQuick.fromJson(Map<String, dynamic> jsonn) {
    return VCharacterQuick(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : null,
      userId: jsonn['user_id'] != null ? jsonn['user_id'].toString() : null,
      name: jsonn['name'] != null ? jsonn['name'].toString() : null,
      avatarUrl: jsonn['avatar_url'] != null
          ? jsonn['avatar_url'].toString()
          : null,
      level: jsonn['level'] != null
          ? int.parse(jsonn['level'].toString())
          : null,
      armorClass: jsonn['armor_class'] != null
          ? int.parse(jsonn['armor_class'].toString())
          : null,
      hitPoints: jsonn['hit_points'] != null
          ? int.parse(jsonn['hit_points'].toString())
          : null,
      abilities: jsonn['abilities'] != null
          ? jsonn['abilities'] as Map<String, dynamic>
          : null,
      race: jsonn['race'] != null ? jsonn['race'].toString() : null,
      classes: jsonn['classes'] != null
          ? jsonn['classes'] as Map<String, dynamic>
          : null,
      dndbeyondCharacterId: jsonn['dndbeyond_character_id'] != null
          ? BigInt.parse(jsonn['dndbeyond_character_id'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
    );
  }

  static Object New({
    String? id,
    String? groupId,
    String? userId,
    String? name,
    String? avatarUrl,
    int? level,
    int? armorClass,
    int? hitPoints,
    Map<String, dynamic>? abilities,
    String? race,
    Map<String, dynamic>? classes,
    BigInt? dndbeyondCharacterId,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (groupId != null) 'group_id': groupId,
      if (userId != null) 'user_id': userId,
      if (name != null) 'name': name,
      if (avatarUrl != null) 'avatar_url': avatarUrl,
      if (level != null) 'level': level,
      if (armorClass != null) 'armor_class': armorClass,
      if (hitPoints != null) 'hit_points': hitPoints,
      if (abilities != null) 'abilities': abilities,
      if (race != null) 'race': race,
      if (classes != null) 'classes': classes,
      if (dndbeyondCharacterId != null)
        'dndbeyond_character_id': dndbeyondCharacterId,
      if (updatedAt != null) 'updated_at': updatedAt,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      groupId: groupId,
      userId: userId,
      name: name,
      avatarUrl: avatarUrl,
      level: level,
      armorClass: armorClass,
      hitPoints: hitPoints,
      abilities: abilities,
      race: race,
      classes: classes,
      dndbeyondCharacterId: dndbeyondCharacterId,
      updatedAt: updatedAt,
    );
  }

  static const _unset = Object();
  VCharacterQuick copyWith({
    Object? id = _unset,
    Object? groupId = _unset,
    Object? userId = _unset,
    Object? name = _unset,
    Object? avatarUrl = _unset,
    Object? level = _unset,
    Object? armorClass = _unset,
    Object? hitPoints = _unset,
    Object? abilities = _unset,
    Object? race = _unset,
    Object? classes = _unset,
    Object? dndbeyondCharacterId = _unset,
    Object? updatedAt = _unset,
  }) {
    return VCharacterQuick(
      id: id == _unset ? this.id : id as String?,
      groupId: groupId == _unset ? this.groupId : groupId as String?,
      userId: userId == _unset ? this.userId : userId as String?,
      name: name == _unset ? this.name : name as String?,
      avatarUrl: avatarUrl == _unset ? this.avatarUrl : avatarUrl as String?,
      level: level == _unset ? this.level : level as int?,
      armorClass: armorClass == _unset ? this.armorClass : armorClass as int?,
      hitPoints: hitPoints == _unset ? this.hitPoints : hitPoints as int?,
      abilities: abilities == _unset
          ? this.abilities
          : abilities as Map<String, dynamic>?,
      race: race == _unset ? this.race : race as String?,
      classes: classes == _unset
          ? this.classes
          : classes as Map<String, dynamic>?,
      dndbeyondCharacterId: dndbeyondCharacterId == _unset
          ? this.dndbeyondCharacterId
          : dndbeyondCharacterId as BigInt?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
    );
  }
}
