// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VEncounterExpandedWithPath
    implements SupadartClass<VEncounterExpandedWithPath> {
  final String? encounterId;
  final String? scopeId;
  final String? campaignId;
  final String? title;
  final String? description;
  final Map<String, dynamic>? content;
  final Map<String, dynamic>? data;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? campaignTitle;
  final String? chapterId;
  final String? chapterOrderNumber;
  final String? chapterTitle;
  final String? adventureId;
  final String? adventureOrderNumber;
  final String? adventureTitle;
  final String? sceneId;
  final String? sceneOrderNumber;
  final String? sceneTitle;
  final String? pathOrder;
  final String? pathTitles;
  final String? encounterCreatureId;
  final String? creatureId;
  final int? quantity;
  final int? initiative;
  final String? notes;
  final String? creatureName;
  final String? creatureKind;
  final num? creatureCr;
  final int? creatureAc;
  final int? creatureHp;

  const VEncounterExpandedWithPath({
    this.encounterId,
    this.scopeId,
    this.campaignId,
    this.title,
    this.description,
    this.content,
    this.data,
    this.createdAt,
    this.updatedAt,
    this.campaignTitle,
    this.chapterId,
    this.chapterOrderNumber,
    this.chapterTitle,
    this.adventureId,
    this.adventureOrderNumber,
    this.adventureTitle,
    this.sceneId,
    this.sceneOrderNumber,
    this.sceneTitle,
    this.pathOrder,
    this.pathTitles,
    this.encounterCreatureId,
    this.creatureId,
    this.quantity,
    this.initiative,
    this.notes,
    this.creatureName,
    this.creatureKind,
    this.creatureCr,
    this.creatureAc,
    this.creatureHp,
  });

  static String get table_name => 'v_encounter_expanded_with_path';
  static String get c_encounterId => 'encounter_id';
  static String get c_scopeId => 'scope_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_title => 'title';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_data => 'data';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_campaignTitle => 'campaign_title';
  static String get c_chapterId => 'chapter_id';
  static String get c_chapterOrderNumber => 'chapter_order_number';
  static String get c_chapterTitle => 'chapter_title';
  static String get c_adventureId => 'adventure_id';
  static String get c_adventureOrderNumber => 'adventure_order_number';
  static String get c_adventureTitle => 'adventure_title';
  static String get c_sceneId => 'scene_id';
  static String get c_sceneOrderNumber => 'scene_order_number';
  static String get c_sceneTitle => 'scene_title';
  static String get c_pathOrder => 'path_order';
  static String get c_pathTitles => 'path_titles';
  static String get c_encounterCreatureId => 'encounter_creature_id';
  static String get c_creatureId => 'creature_id';
  static String get c_quantity => 'quantity';
  static String get c_initiative => 'initiative';
  static String get c_notes => 'notes';
  static String get c_creatureName => 'creature_name';
  static String get c_creatureKind => 'creature_kind';
  static String get c_creatureCr => 'creature_cr';
  static String get c_creatureAc => 'creature_ac';
  static String get c_creatureHp => 'creature_hp';

  static List<VEncounterExpandedWithPath> converter(
    List<Map<String, dynamic>> data,
  ) {
    return data.map(VEncounterExpandedWithPath.fromJson).toList();
  }

  static VEncounterExpandedWithPath converterSingle(Map<String, dynamic> data) {
    return VEncounterExpandedWithPath.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? encounterId,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
    String? encounterCreatureId,
    String? creatureId,
    int? quantity,
    int? initiative,
    String? notes,
    String? creatureName,
    String? creatureKind,
    num? creatureCr,
    int? creatureAc,
    int? creatureHp,
  }) {
    return {
      if (encounterId != null) 'encounter_id': encounterId,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (data != null) 'data': data,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
      if (encounterCreatureId != null)
        'encounter_creature_id': encounterCreatureId,
      if (creatureId != null) 'creature_id': creatureId,
      if (quantity != null) 'quantity': quantity,
      if (initiative != null) 'initiative': initiative,
      if (notes != null) 'notes': notes,
      if (creatureName != null) 'creature_name': creatureName,
      if (creatureKind != null) 'creature_kind': creatureKind,
      if (creatureCr != null) 'creature_cr': creatureCr.toString(),
      if (creatureAc != null) 'creature_ac': creatureAc,
      if (creatureHp != null) 'creature_hp': creatureHp,
    };
  }

  static Map<String, dynamic> insert({
    String? encounterId,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
    String? encounterCreatureId,
    String? creatureId,
    int? quantity,
    int? initiative,
    String? notes,
    String? creatureName,
    String? creatureKind,
    num? creatureCr,
    int? creatureAc,
    int? creatureHp,
  }) {
    return _generateMap(
      encounterId: encounterId,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
      encounterCreatureId: encounterCreatureId,
      creatureId: creatureId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      creatureName: creatureName,
      creatureKind: creatureKind,
      creatureCr: creatureCr,
      creatureAc: creatureAc,
      creatureHp: creatureHp,
    );
  }

  static Map<String, dynamic> update({
    String? encounterId,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
    String? encounterCreatureId,
    String? creatureId,
    int? quantity,
    int? initiative,
    String? notes,
    String? creatureName,
    String? creatureKind,
    num? creatureCr,
    int? creatureAc,
    int? creatureHp,
  }) {
    return _generateMap(
      encounterId: encounterId,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
      encounterCreatureId: encounterCreatureId,
      creatureId: creatureId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      creatureName: creatureName,
      creatureKind: creatureKind,
      creatureCr: creatureCr,
      creatureAc: creatureAc,
      creatureHp: creatureHp,
    );
  }

  factory VEncounterExpandedWithPath.fromJson(Map<String, dynamic> jsonn) {
    return VEncounterExpandedWithPath(
      encounterId: jsonn['encounter_id'] != null
          ? jsonn['encounter_id'].toString()
          : null,
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : null,
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : null,
      title: jsonn['title'] != null ? jsonn['title'].toString() : null,
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : null,
      data: jsonn['data'] != null
          ? jsonn['data'] as Map<String, dynamic>
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      campaignTitle: jsonn['campaign_title'] != null
          ? jsonn['campaign_title'].toString()
          : null,
      chapterId: jsonn['chapter_id'] != null
          ? jsonn['chapter_id'].toString()
          : null,
      chapterOrderNumber: jsonn['chapter_order_number'] != null
          ? jsonn['chapter_order_number'].toString()
          : null,
      chapterTitle: jsonn['chapter_title'] != null
          ? jsonn['chapter_title'].toString()
          : null,
      adventureId: jsonn['adventure_id'] != null
          ? jsonn['adventure_id'].toString()
          : null,
      adventureOrderNumber: jsonn['adventure_order_number'] != null
          ? jsonn['adventure_order_number'].toString()
          : null,
      adventureTitle: jsonn['adventure_title'] != null
          ? jsonn['adventure_title'].toString()
          : null,
      sceneId: jsonn['scene_id'] != null ? jsonn['scene_id'].toString() : null,
      sceneOrderNumber: jsonn['scene_order_number'] != null
          ? jsonn['scene_order_number'].toString()
          : null,
      sceneTitle: jsonn['scene_title'] != null
          ? jsonn['scene_title'].toString()
          : null,
      pathOrder: jsonn['path_order'] != null
          ? jsonn['path_order'].toString()
          : null,
      pathTitles: jsonn['path_titles'] != null
          ? jsonn['path_titles'].toString()
          : null,
      encounterCreatureId: jsonn['encounter_creature_id'] != null
          ? jsonn['encounter_creature_id'].toString()
          : null,
      creatureId: jsonn['creature_id'] != null
          ? jsonn['creature_id'].toString()
          : null,
      quantity: jsonn['quantity'] != null
          ? int.parse(jsonn['quantity'].toString())
          : null,
      initiative: jsonn['initiative'] != null
          ? int.parse(jsonn['initiative'].toString())
          : null,
      notes: jsonn['notes'] != null ? jsonn['notes'].toString() : null,
      creatureName: jsonn['creature_name'] != null
          ? jsonn['creature_name'].toString()
          : null,
      creatureKind: jsonn['creature_kind'] != null
          ? jsonn['creature_kind'].toString()
          : null,
      creatureCr: jsonn['creature_cr'] != null
          ? num.parse(jsonn['creature_cr'].toString())
          : null,
      creatureAc: jsonn['creature_ac'] != null
          ? int.parse(jsonn['creature_ac'].toString())
          : null,
      creatureHp: jsonn['creature_hp'] != null
          ? int.parse(jsonn['creature_hp'].toString())
          : null,
    );
  }

  static Object New({
    String? encounterId,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
    String? encounterCreatureId,
    String? creatureId,
    int? quantity,
    int? initiative,
    String? notes,
    String? creatureName,
    String? creatureKind,
    num? creatureCr,
    int? creatureAc,
    int? creatureHp,
  }) {
    return {
      if (encounterId != null) 'encounter_id': encounterId,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (data != null) 'data': data,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
      if (encounterCreatureId != null)
        'encounter_creature_id': encounterCreatureId,
      if (creatureId != null) 'creature_id': creatureId,
      if (quantity != null) 'quantity': quantity,
      if (initiative != null) 'initiative': initiative,
      if (notes != null) 'notes': notes,
      if (creatureName != null) 'creature_name': creatureName,
      if (creatureKind != null) 'creature_kind': creatureKind,
      if (creatureCr != null) 'creature_cr': creatureCr,
      if (creatureAc != null) 'creature_ac': creatureAc,
      if (creatureHp != null) 'creature_hp': creatureHp,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      encounterId: encounterId,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
      encounterCreatureId: encounterCreatureId,
      creatureId: creatureId,
      quantity: quantity,
      initiative: initiative,
      notes: notes,
      creatureName: creatureName,
      creatureKind: creatureKind,
      creatureCr: creatureCr,
      creatureAc: creatureAc,
      creatureHp: creatureHp,
    );
  }

  static const _unset = Object();
  VEncounterExpandedWithPath copyWith({
    Object? encounterId = _unset,
    Object? scopeId = _unset,
    Object? campaignId = _unset,
    Object? title = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? data = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? campaignTitle = _unset,
    Object? chapterId = _unset,
    Object? chapterOrderNumber = _unset,
    Object? chapterTitle = _unset,
    Object? adventureId = _unset,
    Object? adventureOrderNumber = _unset,
    Object? adventureTitle = _unset,
    Object? sceneId = _unset,
    Object? sceneOrderNumber = _unset,
    Object? sceneTitle = _unset,
    Object? pathOrder = _unset,
    Object? pathTitles = _unset,
    Object? encounterCreatureId = _unset,
    Object? creatureId = _unset,
    Object? quantity = _unset,
    Object? initiative = _unset,
    Object? notes = _unset,
    Object? creatureName = _unset,
    Object? creatureKind = _unset,
    Object? creatureCr = _unset,
    Object? creatureAc = _unset,
    Object? creatureHp = _unset,
  }) {
    return VEncounterExpandedWithPath(
      encounterId: encounterId == _unset
          ? this.encounterId
          : encounterId as String?,
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String?,
      campaignId: campaignId == _unset
          ? this.campaignId
          : campaignId as String?,
      title: title == _unset ? this.title : title as String?,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>?,
      data: data == _unset ? this.data : data as Map<String, dynamic>?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      campaignTitle: campaignTitle == _unset
          ? this.campaignTitle
          : campaignTitle as String?,
      chapterId: chapterId == _unset ? this.chapterId : chapterId as String?,
      chapterOrderNumber: chapterOrderNumber == _unset
          ? this.chapterOrderNumber
          : chapterOrderNumber as String?,
      chapterTitle: chapterTitle == _unset
          ? this.chapterTitle
          : chapterTitle as String?,
      adventureId: adventureId == _unset
          ? this.adventureId
          : adventureId as String?,
      adventureOrderNumber: adventureOrderNumber == _unset
          ? this.adventureOrderNumber
          : adventureOrderNumber as String?,
      adventureTitle: adventureTitle == _unset
          ? this.adventureTitle
          : adventureTitle as String?,
      sceneId: sceneId == _unset ? this.sceneId : sceneId as String?,
      sceneOrderNumber: sceneOrderNumber == _unset
          ? this.sceneOrderNumber
          : sceneOrderNumber as String?,
      sceneTitle: sceneTitle == _unset
          ? this.sceneTitle
          : sceneTitle as String?,
      pathOrder: pathOrder == _unset ? this.pathOrder : pathOrder as String?,
      pathTitles: pathTitles == _unset
          ? this.pathTitles
          : pathTitles as String?,
      encounterCreatureId: encounterCreatureId == _unset
          ? this.encounterCreatureId
          : encounterCreatureId as String?,
      creatureId: creatureId == _unset
          ? this.creatureId
          : creatureId as String?,
      quantity: quantity == _unset ? this.quantity : quantity as int?,
      initiative: initiative == _unset ? this.initiative : initiative as int?,
      notes: notes == _unset ? this.notes : notes as String?,
      creatureName: creatureName == _unset
          ? this.creatureName
          : creatureName as String?,
      creatureKind: creatureKind == _unset
          ? this.creatureKind
          : creatureKind as String?,
      creatureCr: creatureCr == _unset ? this.creatureCr : creatureCr as num?,
      creatureAc: creatureAc == _unset ? this.creatureAc : creatureAc as int?,
      creatureHp: creatureHp == _unset ? this.creatureHp : creatureHp as int?,
    );
  }
}
