// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VEncounterWithPath implements SupadartClass<VEncounterWithPath> {
  final String? id;
  final String? scopeId;
  final String? campaignId;
  final String? title;
  final String? description;
  final Map<String, dynamic>? content;
  final Map<String, dynamic>? data;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final String? campaignTitle;
  final String? chapterId;
  final String? chapterOrderNumber;
  final String? chapterTitle;
  final String? adventureId;
  final String? adventureOrderNumber;
  final String? adventureTitle;
  final String? sceneId;
  final String? sceneOrderNumber;
  final String? sceneTitle;
  final String? pathOrder;
  final String? pathTitles;

  const VEncounterWithPath({
    this.id,
    this.scopeId,
    this.campaignId,
    this.title,
    this.description,
    this.content,
    this.data,
    this.createdAt,
    this.updatedAt,
    this.campaignTitle,
    this.chapterId,
    this.chapterOrderNumber,
    this.chapterTitle,
    this.adventureId,
    this.adventureOrderNumber,
    this.adventureTitle,
    this.sceneId,
    this.sceneOrderNumber,
    this.sceneTitle,
    this.pathOrder,
    this.pathTitles,
  });

  static String get table_name => 'v_encounter_with_path';
  static String get c_id => 'id';
  static String get c_scopeId => 'scope_id';
  static String get c_campaignId => 'campaign_id';
  static String get c_title => 'title';
  static String get c_description => 'description';
  static String get c_content => 'content';
  static String get c_data => 'data';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';
  static String get c_campaignTitle => 'campaign_title';
  static String get c_chapterId => 'chapter_id';
  static String get c_chapterOrderNumber => 'chapter_order_number';
  static String get c_chapterTitle => 'chapter_title';
  static String get c_adventureId => 'adventure_id';
  static String get c_adventureOrderNumber => 'adventure_order_number';
  static String get c_adventureTitle => 'adventure_title';
  static String get c_sceneId => 'scene_id';
  static String get c_sceneOrderNumber => 'scene_order_number';
  static String get c_sceneTitle => 'scene_title';
  static String get c_pathOrder => 'path_order';
  static String get c_pathTitles => 'path_titles';

  static List<VEncounterWithPath> converter(List<Map<String, dynamic>> data) {
    return data.map(VEncounterWithPath.fromJson).toList();
  }

  static VEncounterWithPath converterSingle(Map<String, dynamic> data) {
    return VEncounterWithPath.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (data != null) 'data': data,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  factory VEncounterWithPath.fromJson(Map<String, dynamic> jsonn) {
    return VEncounterWithPath(
      id: jsonn['id'] != null ? jsonn['id'].toString() : null,
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : null,
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : null,
      title: jsonn['title'] != null ? jsonn['title'].toString() : null,
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      content: jsonn['content'] != null
          ? jsonn['content'] as Map<String, dynamic>
          : null,
      data: jsonn['data'] != null
          ? jsonn['data'] as Map<String, dynamic>
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : null,
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : null,
      campaignTitle: jsonn['campaign_title'] != null
          ? jsonn['campaign_title'].toString()
          : null,
      chapterId: jsonn['chapter_id'] != null
          ? jsonn['chapter_id'].toString()
          : null,
      chapterOrderNumber: jsonn['chapter_order_number'] != null
          ? jsonn['chapter_order_number'].toString()
          : null,
      chapterTitle: jsonn['chapter_title'] != null
          ? jsonn['chapter_title'].toString()
          : null,
      adventureId: jsonn['adventure_id'] != null
          ? jsonn['adventure_id'].toString()
          : null,
      adventureOrderNumber: jsonn['adventure_order_number'] != null
          ? jsonn['adventure_order_number'].toString()
          : null,
      adventureTitle: jsonn['adventure_title'] != null
          ? jsonn['adventure_title'].toString()
          : null,
      sceneId: jsonn['scene_id'] != null ? jsonn['scene_id'].toString() : null,
      sceneOrderNumber: jsonn['scene_order_number'] != null
          ? jsonn['scene_order_number'].toString()
          : null,
      sceneTitle: jsonn['scene_title'] != null
          ? jsonn['scene_title'].toString()
          : null,
      pathOrder: jsonn['path_order'] != null
          ? jsonn['path_order'].toString()
          : null,
      pathTitles: jsonn['path_titles'] != null
          ? jsonn['path_titles'].toString()
          : null,
    );
  }

  static Object New({
    String? id,
    String? scopeId,
    String? campaignId,
    String? title,
    String? description,
    Map<String, dynamic>? content,
    Map<String, dynamic>? data,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return {
      if (id != null) 'id': id,
      if (scopeId != null) 'scope_id': scopeId,
      if (campaignId != null) 'campaign_id': campaignId,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (content != null) 'content': content,
      if (data != null) 'data': data,
      if (createdAt != null) 'created_at': createdAt,
      if (updatedAt != null) 'updated_at': updatedAt,
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      scopeId: scopeId,
      campaignId: campaignId,
      title: title,
      description: description,
      content: content,
      data: data,
      createdAt: createdAt,
      updatedAt: updatedAt,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  static const _unset = Object();
  VEncounterWithPath copyWith({
    Object? id = _unset,
    Object? scopeId = _unset,
    Object? campaignId = _unset,
    Object? title = _unset,
    Object? description = _unset,
    Object? content = _unset,
    Object? data = _unset,
    Object? createdAt = _unset,
    Object? updatedAt = _unset,
    Object? campaignTitle = _unset,
    Object? chapterId = _unset,
    Object? chapterOrderNumber = _unset,
    Object? chapterTitle = _unset,
    Object? adventureId = _unset,
    Object? adventureOrderNumber = _unset,
    Object? adventureTitle = _unset,
    Object? sceneId = _unset,
    Object? sceneOrderNumber = _unset,
    Object? sceneTitle = _unset,
    Object? pathOrder = _unset,
    Object? pathTitles = _unset,
  }) {
    return VEncounterWithPath(
      id: id == _unset ? this.id : id as String?,
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String?,
      campaignId: campaignId == _unset
          ? this.campaignId
          : campaignId as String?,
      title: title == _unset ? this.title : title as String?,
      description: description == _unset
          ? this.description
          : description as String?,
      content: content == _unset
          ? this.content
          : content as Map<String, dynamic>?,
      data: data == _unset ? this.data : data as Map<String, dynamic>?,
      createdAt: createdAt == _unset ? this.createdAt : createdAt as DateTime?,
      updatedAt: updatedAt == _unset ? this.updatedAt : updatedAt as DateTime?,
      campaignTitle: campaignTitle == _unset
          ? this.campaignTitle
          : campaignTitle as String?,
      chapterId: chapterId == _unset ? this.chapterId : chapterId as String?,
      chapterOrderNumber: chapterOrderNumber == _unset
          ? this.chapterOrderNumber
          : chapterOrderNumber as String?,
      chapterTitle: chapterTitle == _unset
          ? this.chapterTitle
          : chapterTitle as String?,
      adventureId: adventureId == _unset
          ? this.adventureId
          : adventureId as String?,
      adventureOrderNumber: adventureOrderNumber == _unset
          ? this.adventureOrderNumber
          : adventureOrderNumber as String?,
      adventureTitle: adventureTitle == _unset
          ? this.adventureTitle
          : adventureTitle as String?,
      sceneId: sceneId == _unset ? this.sceneId : sceneId as String?,
      sceneOrderNumber: sceneOrderNumber == _unset
          ? this.sceneOrderNumber
          : sceneOrderNumber as String?,
      sceneTitle: sceneTitle == _unset
          ? this.sceneTitle
          : sceneTitle as String?,
      pathOrder: pathOrder == _unset ? this.pathOrder : pathOrder as String?,
      pathTitles: pathTitles == _unset
          ? this.pathTitles
          : pathTitles as String?,
    );
  }
}
