// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VGroupDashboard implements SupadartClass<VGroupDashboard> {
  final String? groupId;
  final String? groupName;
  final String? dungeonMasterUserId;
  final String? playingCampaignId;
  final BigInt? characterCount;
  final BigInt? sessionLogCount;

  const VGroupDashboard({
    this.groupId,
    this.groupName,
    this.dungeonMasterUserId,
    this.playingCampaignId,
    this.characterCount,
    this.sessionLogCount,
  });

  static String get table_name => 'v_group_dashboard';
  static String get c_groupId => 'group_id';
  static String get c_groupName => 'group_name';
  static String get c_dungeonMasterUserId => 'dungeon_master_user_id';
  static String get c_playingCampaignId => 'playing_campaign_id';
  static String get c_characterCount => 'character_count';
  static String get c_sessionLogCount => 'session_log_count';

  static List<VGroupDashboard> converter(List<Map<String, dynamic>> data) {
    return data.map(VGroupDashboard.fromJson).toList();
  }

  static VGroupDashboard converterSingle(Map<String, dynamic> data) {
    return VGroupDashboard.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? groupId,
    String? groupName,
    String? dungeonMasterUserId,
    String? playingCampaignId,
    BigInt? characterCount,
    BigInt? sessionLogCount,
  }) {
    return {
      if (groupId != null) 'group_id': groupId,
      if (groupName != null) 'group_name': groupName,
      if (dungeonMasterUserId != null)
        'dungeon_master_user_id': dungeonMasterUserId,
      if (playingCampaignId != null) 'playing_campaign_id': playingCampaignId,
      if (characterCount != null) 'character_count': characterCount.toString(),
      if (sessionLogCount != null)
        'session_log_count': sessionLogCount.toString(),
    };
  }

  static Map<String, dynamic> insert({
    String? groupId,
    String? groupName,
    String? dungeonMasterUserId,
    String? playingCampaignId,
    BigInt? characterCount,
    BigInt? sessionLogCount,
  }) {
    return _generateMap(
      groupId: groupId,
      groupName: groupName,
      dungeonMasterUserId: dungeonMasterUserId,
      playingCampaignId: playingCampaignId,
      characterCount: characterCount,
      sessionLogCount: sessionLogCount,
    );
  }

  static Map<String, dynamic> update({
    String? groupId,
    String? groupName,
    String? dungeonMasterUserId,
    String? playingCampaignId,
    BigInt? characterCount,
    BigInt? sessionLogCount,
  }) {
    return _generateMap(
      groupId: groupId,
      groupName: groupName,
      dungeonMasterUserId: dungeonMasterUserId,
      playingCampaignId: playingCampaignId,
      characterCount: characterCount,
      sessionLogCount: sessionLogCount,
    );
  }

  factory VGroupDashboard.fromJson(Map<String, dynamic> jsonn) {
    return VGroupDashboard(
      groupId: jsonn['group_id'] != null ? jsonn['group_id'].toString() : null,
      groupName: jsonn['group_name'] != null
          ? jsonn['group_name'].toString()
          : null,
      dungeonMasterUserId: jsonn['dungeon_master_user_id'] != null
          ? jsonn['dungeon_master_user_id'].toString()
          : null,
      playingCampaignId: jsonn['playing_campaign_id'] != null
          ? jsonn['playing_campaign_id'].toString()
          : null,
      characterCount: jsonn['character_count'] != null
          ? BigInt.parse(jsonn['character_count'].toString())
          : null,
      sessionLogCount: jsonn['session_log_count'] != null
          ? BigInt.parse(jsonn['session_log_count'].toString())
          : null,
    );
  }

  static Object New({
    String? groupId,
    String? groupName,
    String? dungeonMasterUserId,
    String? playingCampaignId,
    BigInt? characterCount,
    BigInt? sessionLogCount,
  }) {
    return {
      if (groupId != null) 'group_id': groupId,
      if (groupName != null) 'group_name': groupName,
      if (dungeonMasterUserId != null)
        'dungeon_master_user_id': dungeonMasterUserId,
      if (playingCampaignId != null) 'playing_campaign_id': playingCampaignId,
      if (characterCount != null) 'character_count': characterCount,
      if (sessionLogCount != null) 'session_log_count': sessionLogCount,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      groupId: groupId,
      groupName: groupName,
      dungeonMasterUserId: dungeonMasterUserId,
      playingCampaignId: playingCampaignId,
      characterCount: characterCount,
      sessionLogCount: sessionLogCount,
    );
  }

  static const _unset = Object();
  VGroupDashboard copyWith({
    Object? groupId = _unset,
    Object? groupName = _unset,
    Object? dungeonMasterUserId = _unset,
    Object? playingCampaignId = _unset,
    Object? characterCount = _unset,
    Object? sessionLogCount = _unset,
  }) {
    return VGroupDashboard(
      groupId: groupId == _unset ? this.groupId : groupId as String?,
      groupName: groupName == _unset ? this.groupName : groupName as String?,
      dungeonMasterUserId: dungeonMasterUserId == _unset
          ? this.dungeonMasterUserId
          : dungeonMasterUserId as String?,
      playingCampaignId: playingCampaignId == _unset
          ? this.playingCampaignId
          : playingCampaignId as String?,
      characterCount: characterCount == _unset
          ? this.characterCount
          : characterCount as BigInt?,
      sessionLogCount: sessionLogCount == _unset
          ? this.sessionLogCount
          : sessionLogCount as BigInt?,
    );
  }
}
