// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VScopePath implements SupadartClass<VScopePath> {
  final String? scopeId;
  final String? scopeType;
  final String? campaignId;
  final String? campaignTitle;
  final String? chapterId;
  final String? chapterOrderNumber;
  final String? chapterTitle;
  final String? adventureId;
  final String? adventureOrderNumber;
  final String? adventureTitle;
  final String? sceneId;
  final String? sceneOrderNumber;
  final String? sceneTitle;
  final String? pathOrder;
  final String? pathTitles;

  const VScopePath({
    this.scopeId,
    this.scopeType,
    this.campaignId,
    this.campaignTitle,
    this.chapterId,
    this.chapterOrderNumber,
    this.chapterTitle,
    this.adventureId,
    this.adventureOrderNumber,
    this.adventureTitle,
    this.sceneId,
    this.sceneOrderNumber,
    this.sceneTitle,
    this.pathOrder,
    this.pathTitles,
  });

  static String get table_name => 'v_scope_path';
  static String get c_scopeId => 'scope_id';
  static String get c_scopeType => 'scope_type';
  static String get c_campaignId => 'campaign_id';
  static String get c_campaignTitle => 'campaign_title';
  static String get c_chapterId => 'chapter_id';
  static String get c_chapterOrderNumber => 'chapter_order_number';
  static String get c_chapterTitle => 'chapter_title';
  static String get c_adventureId => 'adventure_id';
  static String get c_adventureOrderNumber => 'adventure_order_number';
  static String get c_adventureTitle => 'adventure_title';
  static String get c_sceneId => 'scene_id';
  static String get c_sceneOrderNumber => 'scene_order_number';
  static String get c_sceneTitle => 'scene_title';
  static String get c_pathOrder => 'path_order';
  static String get c_pathTitles => 'path_titles';

  static List<VScopePath> converter(List<Map<String, dynamic>> data) {
    return data.map(VScopePath.fromJson).toList();
  }

  static VScopePath converterSingle(Map<String, dynamic> data) {
    return VScopePath.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? scopeId,
    String? scopeType,
    String? campaignId,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return {
      if (scopeId != null) 'scope_id': scopeId,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
    };
  }

  static Map<String, dynamic> insert({
    String? scopeId,
    String? scopeType,
    String? campaignId,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  static Map<String, dynamic> update({
    String? scopeId,
    String? scopeType,
    String? campaignId,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  factory VScopePath.fromJson(Map<String, dynamic> jsonn) {
    return VScopePath(
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : null,
      scopeType: jsonn['scope_type'] != null
          ? jsonn['scope_type'].toString()
          : null,
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : null,
      campaignTitle: jsonn['campaign_title'] != null
          ? jsonn['campaign_title'].toString()
          : null,
      chapterId: jsonn['chapter_id'] != null
          ? jsonn['chapter_id'].toString()
          : null,
      chapterOrderNumber: jsonn['chapter_order_number'] != null
          ? jsonn['chapter_order_number'].toString()
          : null,
      chapterTitle: jsonn['chapter_title'] != null
          ? jsonn['chapter_title'].toString()
          : null,
      adventureId: jsonn['adventure_id'] != null
          ? jsonn['adventure_id'].toString()
          : null,
      adventureOrderNumber: jsonn['adventure_order_number'] != null
          ? jsonn['adventure_order_number'].toString()
          : null,
      adventureTitle: jsonn['adventure_title'] != null
          ? jsonn['adventure_title'].toString()
          : null,
      sceneId: jsonn['scene_id'] != null ? jsonn['scene_id'].toString() : null,
      sceneOrderNumber: jsonn['scene_order_number'] != null
          ? jsonn['scene_order_number'].toString()
          : null,
      sceneTitle: jsonn['scene_title'] != null
          ? jsonn['scene_title'].toString()
          : null,
      pathOrder: jsonn['path_order'] != null
          ? jsonn['path_order'].toString()
          : null,
      pathTitles: jsonn['path_titles'] != null
          ? jsonn['path_titles'].toString()
          : null,
    );
  }

  static Object New({
    String? scopeId,
    String? scopeType,
    String? campaignId,
    String? campaignTitle,
    String? chapterId,
    String? chapterOrderNumber,
    String? chapterTitle,
    String? adventureId,
    String? adventureOrderNumber,
    String? adventureTitle,
    String? sceneId,
    String? sceneOrderNumber,
    String? sceneTitle,
    String? pathOrder,
    String? pathTitles,
  }) {
    return {
      if (scopeId != null) 'scope_id': scopeId,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
      if (campaignTitle != null) 'campaign_title': campaignTitle,
      if (chapterId != null) 'chapter_id': chapterId,
      if (chapterOrderNumber != null)
        'chapter_order_number': chapterOrderNumber,
      if (chapterTitle != null) 'chapter_title': chapterTitle,
      if (adventureId != null) 'adventure_id': adventureId,
      if (adventureOrderNumber != null)
        'adventure_order_number': adventureOrderNumber,
      if (adventureTitle != null) 'adventure_title': adventureTitle,
      if (sceneId != null) 'scene_id': sceneId,
      if (sceneOrderNumber != null) 'scene_order_number': sceneOrderNumber,
      if (sceneTitle != null) 'scene_title': sceneTitle,
      if (pathOrder != null) 'path_order': pathOrder,
      if (pathTitles != null) 'path_titles': pathTitles,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
      campaignTitle: campaignTitle,
      chapterId: chapterId,
      chapterOrderNumber: chapterOrderNumber,
      chapterTitle: chapterTitle,
      adventureId: adventureId,
      adventureOrderNumber: adventureOrderNumber,
      adventureTitle: adventureTitle,
      sceneId: sceneId,
      sceneOrderNumber: sceneOrderNumber,
      sceneTitle: sceneTitle,
      pathOrder: pathOrder,
      pathTitles: pathTitles,
    );
  }

  static const _unset = Object();
  VScopePath copyWith({
    Object? scopeId = _unset,
    Object? scopeType = _unset,
    Object? campaignId = _unset,
    Object? campaignTitle = _unset,
    Object? chapterId = _unset,
    Object? chapterOrderNumber = _unset,
    Object? chapterTitle = _unset,
    Object? adventureId = _unset,
    Object? adventureOrderNumber = _unset,
    Object? adventureTitle = _unset,
    Object? sceneId = _unset,
    Object? sceneOrderNumber = _unset,
    Object? sceneTitle = _unset,
    Object? pathOrder = _unset,
    Object? pathTitles = _unset,
  }) {
    return VScopePath(
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String?,
      scopeType: scopeType == _unset ? this.scopeType : scopeType as String?,
      campaignId: campaignId == _unset
          ? this.campaignId
          : campaignId as String?,
      campaignTitle: campaignTitle == _unset
          ? this.campaignTitle
          : campaignTitle as String?,
      chapterId: chapterId == _unset ? this.chapterId : chapterId as String?,
      chapterOrderNumber: chapterOrderNumber == _unset
          ? this.chapterOrderNumber
          : chapterOrderNumber as String?,
      chapterTitle: chapterTitle == _unset
          ? this.chapterTitle
          : chapterTitle as String?,
      adventureId: adventureId == _unset
          ? this.adventureId
          : adventureId as String?,
      adventureOrderNumber: adventureOrderNumber == _unset
          ? this.adventureOrderNumber
          : adventureOrderNumber as String?,
      adventureTitle: adventureTitle == _unset
          ? this.adventureTitle
          : adventureTitle as String?,
      sceneId: sceneId == _unset ? this.sceneId : sceneId as String?,
      sceneOrderNumber: sceneOrderNumber == _unset
          ? this.sceneOrderNumber
          : sceneOrderNumber as String?,
      sceneTitle: sceneTitle == _unset
          ? this.sceneTitle
          : sceneTitle as String?,
      pathOrder: pathOrder == _unset ? this.pathOrder : pathOrder as String?,
      pathTitles: pathTitles == _unset
          ? this.pathTitles
          : pathTitles as String?,
    );
  }
}
