// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison, prefer_null_aware_operators
// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the Supadart configuration.
import 'supadart_header.dart';

class VScopeCampaign implements SupadartClass<VScopeCampaign> {
  final String? scopeId;
  final String? scopeType;
  final String? campaignId;

  const VScopeCampaign({this.scopeId, this.scopeType, this.campaignId});

  static String get table_name => 'v_scope_campaign';
  static String get c_scopeId => 'scope_id';
  static String get c_scopeType => 'scope_type';
  static String get c_campaignId => 'campaign_id';

  static List<VScopeCampaign> converter(List<Map<String, dynamic>> data) {
    return data.map(VScopeCampaign.fromJson).toList();
  }

  static VScopeCampaign converterSingle(Map<String, dynamic> data) {
    return VScopeCampaign.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? scopeId,
    String? scopeType,
    String? campaignId,
  }) {
    return {
      if (scopeId != null) 'scope_id': scopeId,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
    };
  }

  static Map<String, dynamic> insert({
    String? scopeId,
    String? scopeType,
    String? campaignId,
  }) {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
    );
  }

  static Map<String, dynamic> update({
    String? scopeId,
    String? scopeType,
    String? campaignId,
  }) {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
    );
  }

  factory VScopeCampaign.fromJson(Map<String, dynamic> jsonn) {
    return VScopeCampaign(
      scopeId: jsonn['scope_id'] != null ? jsonn['scope_id'].toString() : null,
      scopeType: jsonn['scope_type'] != null
          ? jsonn['scope_type'].toString()
          : null,
      campaignId: jsonn['campaign_id'] != null
          ? jsonn['campaign_id'].toString()
          : null,
    );
  }

  static Object New({String? scopeId, String? scopeType, String? campaignId}) {
    return {
      if (scopeId != null) 'scope_id': scopeId,
      if (scopeType != null) 'scope_type': scopeType,
      if (campaignId != null) 'campaign_id': campaignId,
    };
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      scopeId: scopeId,
      scopeType: scopeType,
      campaignId: campaignId,
    );
  }

  static const _unset = Object();
  VScopeCampaign copyWith({
    Object? scopeId = _unset,
    Object? scopeType = _unset,
    Object? campaignId = _unset,
  }) {
    return VScopeCampaign(
      scopeId: scopeId == _unset ? this.scopeId : scopeId as String?,
      scopeType: scopeType == _unset ? this.scopeType : scopeType as String?,
      campaignId: campaignId == _unset
          ? this.campaignId
          : campaignId as String?,
    );
  }
}
